spring.application.name=jwt_authentication
# Database connection configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=PgSQL225
spring.jpa.properties.hibernate.format_sql=true


# Hibernate settings (make sure to turn off ddl-auto to avoid conflicts)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt_secret=bXktc2VjcmV0LTMyLWJpdC1lbmNvZGVkLWtleS1mb3ItcnVubmluZy1teS1hcHA=
expire_time=3600000